os:
  - linux
language: go
sudo: required
go:
- 1.11.x
dist: trusty
addons:
  sonarcloud:
    organization: "paysuper"
services:
- mongodb
stages:
- test
- name: deploy
  if: branch IN (master, feature/PAY-261)
env:
  global:
  - GO111MODULE=on
  - secure: QY9Ftc+Vn+0VVaBVca7gI/ia5bUTbw9l99UqKOnSGY8NSeyIpkWZ0v0cbK6nGUG5uvsq8HtPNvwd5K7a7Z3ccpIVK1Hnz+azRZq2VT2jXi6NA7FMz5D6ooiSfRsccdGNCRDcroYclMRK7d2txssprs7ab+jbFbThTa8Nvmv9nO2nu956Z/xTygVthoADuW8uBtYX+3usuNfOZuTM67hWUGpCCZlkoVRjiAr3aueI+V8oZ3MVvwBvx+gXQKOtKUa3RxWH6FOY2T2CIr1v7QB2typF1eh+96upMiJsK/a7tIXwb+mEPg63oPZKMtdWwTFrONWhjAM6Q5ivROw9kJAmGlsBDPSW6WiMbLgvIgfutaC/H4Jh3Hhc+37wh4pYyWvWi71l2J1FaDryQAG62N4sW2VAOnMz/7usOi3VqOa5vJOc8JJM8tMzsCYwax0laWDOOuBa77pA0LuuNkb8f9ufBxZyOii6lHf/0JWafMaw+5fdsmtuuPfruOLJec7ovu30Or8CWYVXDkWon+cI7KI4WF80bMBlKJ9CfRBYboTI5yIKGz48wYNvWUbYQ5UeRQMY8SYdpDmTMgGjmas+8wyE7Gik+NOvd6E06s/L4G9zvi1IJHa5ODcZwoZ6b6xP3br/XDmQQKAHg6CUgnK3+3rWn60n3tBKGYpNJbaQHrmmxFE=
  - secure: TtAyIoi5x0CnnX+URtjavWgzRTmnAuAjBIq/Z6rwbMCkSeziovbjDckoYy4XTMBs1+CsjmE53goc2zmUTjuRmg3oCj4cHVx13Gp/AQWZlbItVHB34RCA+0AmnrDT8VVys6FK+W2Et3vxJBduVLYJO222AayTB6NqL0tT44JSnrvSrk0HMNiuNhAA1GyJNlrKkqVlqrAsvrCxxlvuJ1tDnqtbWNQDh/PMBL33h+J0+iAaVJMYvN0otarPQsx0URTilP6i8pK2YR5nr0RH8hy4mg7Fantz8uYptDvNy6OLePmVTSQiNBPmPU7E7qR6UYOXwg9c8PxGrpimm2fQDHVjVZd4oTyBbygm3BKdF8I4W543K0D/Qfs1d/vCInIGdi+i7JwzQiyFJqHK6gAFgyb1yN5LXH9YuM5JbFff9zSPFOJEUEz/csWlWF3InCvxNvMhCIqSnk/IWcmDOLYrUcAcQhzPjfDSIvKhrq/2ah0whZMhfFZi8bhv7Swwptf95rXagOhAYT6Zw6fvXWnuYZB8tlROqVfbjG1YziBLXM+saUEB8Qzf2ST2tXcXK6xvh+Sbn1fFKIg6o/Lq4DlIkUs76ZqWupim7/dBwfoJ+MMvyA5QIPQA3TKirO0svlVqi9aH0vdQ1W5LspiZsSSKEw3Tz0Np8zdb3NrrIZXGSHaUDvw=
  - secure: nw9HK65Bp65Bn5eaebuGwUm83PiJFxkm+EgDOp626Xyw/tsiOqZwu3MIC3/PBfYZinzKKHIrDsRbv1+jokSr+0HDZORj4nTL3ovWC7CB6xtpRQ1jeeFTKXWf1789QDZSnFhvZ1wNJmUgWKK4Ma9SsSRecNIVzIEWEt8T2zOO345xoZGEaYgOy1VMJVKR93WjvOZ5lJ7szP88MG+L4mnE+zE8aAkDMQFNeO0MTlrpjwRZHMqoEH0tclUmo656qium0R5NIYVvF7oL4KgU5WSCeL8fys1snhl/rUbijBSiB1G3qtiXviIThQ2xgdmHQ/PIbyk+sozwk48shyiMT+EotasIoDUYX/nigqJXtEj7XZ+ScJzT95Z3k/M8lKySxUE5f9yv61oW47J+6SACnm9xc/12EuX7rgQiiQNRs28OrG25GtTsgnaElixnALzy4Uzj25LqV/Gf6tR358paKS/IwwhV478FFrzHlLwWZsRKHDGrO5nVXoMed8GmrpAuFG8NNUdu+T4pCJJdT3XXI3H8etKRAZ8kHCEvBgxGSkd/cX8axd90IHCFCMz5kZl+WlXX74vqtTPVGdv4e4zsXGzDHKOpp2AiCjxy0JuduEN4mdKFwn19VqPKhNus5uTXqQvvGHYed4EDYKINr9UWqc/Pq0Gc1T5j0/QtqFGg8rd1u+I=
  - secure: B52LkTAJSICFGEHhZzNhUtX1485qvn2Le0m2lz4tcqFC4CcvYTUqpE76xzNO9PpzyUkhBbK/PlEOhF95EeieYK0MQPtUFJOeh8RWIZ1wmIIvYt4jBVwc2HAfQlARH8SCznfXGzo1lLul67oybbvDxeEaIuKdk1EQDDpGljq7nzIGTGo5jq4YnPGNW7uBK/o13Fl/Owjd1ziQbrsUZJHFLKWFX32URSgQOvy/DV6ZJrqVeWsffJfGAlR/QVPtiMpVeijX55W8i6OJjcruWK1hR4C4ooNGfdF+iCD/7JzekpQP+rwa87lxFghm8g80d/lIq6CRl2RYj5VhylBlH7E2rn8IBT7le3olM8C2Qy5qDEbNL0lOTm8/rpK6hEpYJ2kMcRdNnvrRfvKS0P4sIoFNz1GzncmyO6l1quivvTFSoefv3bCqp57LkHmJKomCBLl4yltXcmEODa15pElIApkwKMmOAVmxubk6BUjV1n/o3IexRIgH5ugh7bVxdACrAz4Gq+4Q8nHzu+fVsd1OTIHHA+z0St08VCG2xpOwyjeCZU5itEiAVrTCuDAJqegbsSTW9q98BlGABlcjNCtHgPi3WW5Ckf9pdp2uPA04Kq2zvslG7KNvDtwxXtbzJzPeLBqX/NHu021ppEXM/9v9XlrbP1jZVXB0tQ9iHio09cO09Jg=
  - secure: LznyL/Pm3o0yiIJV36D/PMu7vpq0tJUjEsP2TZqbiR3YDHmn6IGZweJK1fISMVCsSW8NKz0bJnh6TwEckyA/SF9XK8XhkT9C1ZzcQn/LloF9k8XZZaZUFRepL7xp3ZL5lGqxmVeb4H5h7SDIhbEft5eyUrslGQtjms8h71qkuHvPE57iNeO+NPxNe2mR1tfoJxLT4L/lYy0bu8L77QcPncpZk6pMuGtka9108rrbUwTF0IokyGlwpjgpbH8wY41SVbWxhutCUzuA4STgxDNUtfLig+k8WRTGce6WTQa+J/dP/7sn8SrXyfO9yxfdrdwX6pdEPvyIS4oi3FdqpiRnU8kQDxng/RsDgIUDSooFiRB7PK1/EBp64nq9gV9vLEGlI/cVF9UjayockftCgT0M9oP1qbUNtxczjGAe8+VBuQcW2Z48/eu67mEt+FQN1pzcOZcYhyOqxhfGjKUqtyQozGvbJ8+NcZxcFmcFnrzB3Kk3aq+SPGxvEjgycI3XYV8PIpGKcG7cYvvgGbVk9rD2l+pAn8pYgQrAsWIrQxHmuOEWM2/74W/W/xyVPDswjoOVkQeEFK5v7qzTzz3Zj46N4PDMQAgbBVh9vDAdMsvS2v+JW53L0/eoiQV5JS7My/QPmHIyNmJPu8YRXfsFDldO6WWNJ0QBlRGcdy0NsEl2WTM=
before_install:
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin
jobs:
  include:
  - stage: test
    install: true
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
    - sonar-scanner
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
notifications:
  email: false
  slack:
    secure: TNjvJwLocb9aJHFv+KECW/09dTTqRl4jE2p+MKDnr2uf+CqfDAjsanx2eEPjw9rUeSPfJUQ1ZUVTyv+nQKslMippgCpz9Wo9+PPw/gaNoY5niVpNPRE2TmjKyZoDx8xYYfXi+gwUWWOz6hHCv6Vb1edBmDvsoXXSuNuUxYLsUjN9mDFDutrFNC29K9iDfTHr9yBgVmjffOdph0dtybpr6aunBXnvVhBIX/XNNf697Yu6DkJAOfSPcCbREXmR/J5BGwNAgEA/jBH5XjLdYFyuJGHuDAAgOv0OPPC6Laly4cb+6yb7cqjD8iN1RnQm5k1hFBFYZA7lWjy9bHcf24pzGg2dHSvSEuFGpvV6EKx2wv7rWSPpQM5tug0nDTGJJAU23iKWsXK7cmjb11m3acrKyUj84ckmmBrRD9urUGOISphOYynclg2em7jRh64lf4aLoO8ErFm2VlD+KCN1qTBblIHPm6h2aUaT0WPlekYXssh177xfroLuO6QZIwj+4ipP9/but2vqA0jXyzk2jAl4fUrowDH0+VbWxpaYE0YYbt8VgyZpn/TbJv3C0Ni58/txOeKcUmoYOiZuJqOPWiIWpjixCrtru8lvck28EyIH3IQCqN5WZ8beBkC2HQKsZu+ktTATRYrghprqGmaAqbWr17JZ6mob/rXvNE4+PtPNow4=
