os:
- linux
language: go
sudo: required
go:
- 1.11.x
dist: trusty
addons:
  sonarcloud:
    organization: paysuper
services:
- mongodb
stages:
- test
- name: deploy
  if: branch = master
env:
  global:
  - GO111MODULE=on
  - secure: nI0jDZVLDm3hulnwi/lvi3sMJ3U42AF3nRbhcyVEpO9hbdYCMDRs19ISquFB+sMXFQxxQHANWnOZUSIzmZzDiRrO3RdSEBtOGa0tO5jAht7haylnh7Whmkf+YYLsCYu4Is3lbglwJFa0NtLpQocGATcvK3JJnUAVVPiin0HYYoWU6S2k+2sws0toBRyuNtJ3/E13HuUByfKf3PDTNDEamYy2ZVvHBNk7/55XtfXPJW8ThURSUlHrunSUX7TAtFlE35Ol6MTNGmnJ2dw3KApmmel+3t77IFQnkyxwk3E6ZPjUFaOnixN3fSAIuVUWWUMixOOk/Qp5UqxjcV694pS/WAI1PDwN1K/NE73iAyrFJlANZYvyh/4V0QXKg3Y4xuQ8g2b6PZKxx7glPvYrMJR90PJxwXjn9Ze8HQ3/H8K6/K958Bn+iqPVY5DUAL6K0W1djTFd8TzMvL486kzPITKp18xDjvSHhtRIyQKyOrzuSo1hJZlGgyZ4Iw3Dr9EYXNFD/ETsAgXgJ8K/y3qy8JAPj++Lm1uWdfC/sj1utqGXGBDcsQbo0HoETaW9enqLuVri/xHdHCkTJeqt975Zr0NrDLDb6v2I34H2Jgy3HSk0kKrATrHNkgxrKrDGxFJ+bW8FghplDCjSph/tMM0O48KV6n12SPmaFga3DqsUF2aGtZ4=
  - secure: MBEadocmb54e5MDHfLBgjy1iJsHwghVzUFNAEHcQIccVLwIGvYbupfyURKX8VClEHx5SY1uesNHZE44XrNesm4dVAP8HQ7VIUd0VbJWHTUL780eBjveHcrvg2YKEThRMkeIEeWC/ViwpZiyYhTzhnKRM4A9DCKzCL0pTQMxzcUd3/RT727qCCgY9Ww07u5jLuGzXwJkj0TEepGjeuXCoMw4MAk7CFVo5/gWRy6wmDah3vYNDeEaYMmNIkiyf6q13lnuXZUDADGtocsFsUEH4avkE+deWoS1UL7lyB6iVTJ5G5QPrd4oh7xgFakJHWRfC9t0xe++E3snFBZUBgKiYCPFTSWKGW0v/L2YlXYW4K5mquaUthYDIow4jTtmoECyfbTIwDruB+MG7GNwDHw1mQrfqk4130MODVoyVHDYUYyTzR5s4REwG/fa7eCnyDjfUw7y2w0bKozo0tcqCOfoOcrndocDsmKRxIDj3nocCp88amAm9EVyps+cfAn5YX35QRaMvv3oX5lntsLigQ1uHp8tHT8e0hHQV2hszgMgMdOJFBS+TLosA0/9z78x4rgQJ4GAJfKSP4OBkWhbtNVB2Wa/9PE+u0Q4Y7KFfubFBH+fASZM2S7YfikqsvB8hmq7Lcr01vhhS2rQ55WwkmotgUw4FoldrihrJAZPgGQIvkpg=
  - secure: ZO9k1CybHRJL0BDarCl5pKAPNzlx5pPpOvtVhgz4Fyc7RsaD6TTsIu6PNUhBWXQ9bMo3wGAIFodya9jKpmHygyeXjTup0L70Et/1UXp72iWAnvN/gKrJmQnzgizDl8z6cNLH6QsxpFW1uaImbWtk/TCtZcTFMhXtAJJIJ9vHqYl/f2i007ZBg5VlcnnUuOKYrSR0nbK8LR5wO2nL7SeFVnHB6x9ph5Gr/YUyHSCR3uXyb/76dbjnC4gApethQmYx4hXX/dxU9Y4ph4JdhS5hU1KJW6L199F6Aspul2cD3Vgyas2SwsIRTzGDDv5x2RXYdbYklrXDCkY2itMc8n4OIv2rYnBIjves1Qtz+fIBuTSWUCPuPLBwzkPgJyb82LA87azfsb0S+l4fbsU5lx3qNqaR1Dh5ammN8S0cLRHcEmiTOg8UfFBSQpvOIp5szUpTk2I1QvDGhGTthQbSzxZ0eevBLGUyGlYdFts0Ohfc1kMCYwfcABwR42jRnbMjP7LXb7wilCcG8SqUtguZ73IoB4ALTK0Aa7wPtd3Z+bWFoe9UfUNWl6f1sjdHMdhKj7hOv71rwqWxChKwLP6NZ+wrFb4F5fIuBaH+FLMgUywyjCT3Dz7+sNqwXgMV3whmjkphEkGxavMPnflP5Kf6DulTwj/5RhNQvb8GK9f+RiRzawM=
before_install:
- wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
- tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
- sudo mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin
jobs:
  include:
  - stage: test
    install: true
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
    - sonar-scanner
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
notifications:
  email: false
  slack:
    secure: TNjvJwLocb9aJHFv+KECW/09dTTqRl4jE2p+MKDnr2uf+CqfDAjsanx2eEPjw9rUeSPfJUQ1ZUVTyv+nQKslMippgCpz9Wo9+PPw/gaNoY5niVpNPRE2TmjKyZoDx8xYYfXi+gwUWWOz6hHCv6Vb1edBmDvsoXXSuNuUxYLsUjN9mDFDutrFNC29K9iDfTHr9yBgVmjffOdph0dtybpr6aunBXnvVhBIX/XNNf697Yu6DkJAOfSPcCbREXmR/J5BGwNAgEA/jBH5XjLdYFyuJGHuDAAgOv0OPPC6Laly4cb+6yb7cqjD8iN1RnQm5k1hFBFYZA7lWjy9bHcf24pzGg2dHSvSEuFGpvV6EKx2wv7rWSPpQM5tug0nDTGJJAU23iKWsXK7cmjb11m3acrKyUj84ckmmBrRD9urUGOISphOYynclg2em7jRh64lf4aLoO8ErFm2VlD+KCN1qTBblIHPm6h2aUaT0WPlekYXssh177xfroLuO6QZIwj+4ipP9/but2vqA0jXyzk2jAl4fUrowDH0+VbWxpaYE0YYbt8VgyZpn/TbJv3C0Ni58/txOeKcUmoYOiZuJqOPWiIWpjixCrtru8lvck28EyIH3IQCqN5WZ8beBkC2HQKsZu+ktTATRYrghprqGmaAqbWr17JZ6mob/rXvNE4+PtPNow4=
