{{- $deployment := .Values.backend -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations: 
    released: {{ .Release.Time}}    
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $deployment.role }}
  replicas: {{ $deployment.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $deployment.role }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      volumes:
      - name: {{ .Chart.Name }}-cardpay
        secret:
          secretName: {{ .Chart.Name }}-cardpay
      containers:
      - name: {{ $deployment.name }}
        image: {{ $deployment.image }}:{{ $deployment.imageTag }}
        volumeMounts:
        - name: {{ .Chart.Name }}-cardpay
          mountPath: /application/config/parameters
          readOnly: true
        env:
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:{{ $deployment.port }}"
        - name: MICRO_REGISTRY
          value: "kubernetes"
        - name: MICRO_SELECTOR
          value: "static"
        - name: METRICS_PORT
          value: "{{ $deployment.healthPort }}"
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-mongo-connection
              key: MONGO_HOST
        - name: MONGO_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-mongo-connection
              key: MONGO_DB
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-mongo-connection
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-mongo-connection
              key: MONGO_PASSWORD
        - name: JWT_SIGNATURE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-jwt-secret
              key: {{ .Chart.Name }}-jwt-secret
        - name: AUTH1_ISSUER
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-auth1
              key: AUTH1_ISSUER
        - name: AUTH1_CLIENTID
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-auth1
              key: AUTH1_CLIENTID
        - name: AUTH1_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-auth1
              key: AUTH1_CLIENTSECRET
        - name: AUTH1_REDIRECTURL
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-auth1
              key: AUTH1_REDIRECTURL
        ports:
        - containerPort: {{$deployment.port}}
        #livenessProbe:
        #  httpGet:
        #    path: /health
        #    port: {{ $deployment.healthPort }}
        #  initialDelaySeconds: 15
        #  timeoutSeconds: 1
        #  failureThreshold: 3
        #  periodSeconds: 5
        #volumeMounts:
        #- name: {{ $deploymentName }}-config
        #  mountPath: /application/etc/
        #  readOnly: tru